<?php

namespace Database\Seeders;

use App\Models\AnimalReport;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class AnimalReportsSeeder extends Seeder
{
    public function run()
    {
        // Clear existing data
        AnimalReport::truncate();

        $reports = [
            [
                'animal_species' => 'Dog',
                'animal_type' => 'Sick/Injured',
                'other_species' => null,
                'description' => 'Found a limping golden retriever near Central Park. Seems to have an injured front leg.',
                'location' => 'Central Park, Main Entrance',
                'last_seen' => Carbon::now()->subHours(2),
                'animal_photo' => 'storage/animal-photos/dog1.jpg',
                'contact_name' => 'John Doe',
                'contact_phone' => '555-1234',
                'contact_email' => 'john@example.com',
                'report_id' => 'SP-ABC12345',
                'status' => 'In Progress',
                'expires_at' => Carbon::now()->addDays(30),
                'created_at' => Carbon::now()->subHours(2),
                'updated_at' => Carbon::now()->subHours(1),
            ],
            [
                'animal_species' => 'Cat',
                'animal_type' => 'Stray/Lost',
                'other_species' => null,
                'description' => 'Friendly tabby cat without collar, appears lost. Hanging around 5th Avenue.',
                'location' => '5th Avenue & 42nd Street',
                'last_seen' => Carbon::now()->subDays(1),
                'animal_photo' => 'storage/animal-photos/cat1.jpg',
                'contact_name' => 'Jane Smith',
                'contact_phone' => '555-5678',
                'contact_email' => 'jane@example.com',
                'report_id' => 'SP-DEF67890',
                'status' => 'Resolved',
                'expires_at' => Carbon::now()->addDays(30),
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subHours(6),
            ],
            [
                'animal_species' => 'Dog',
                'animal_type' => 'Aggressive',
                'other_species' => null,
                'description' => 'Large German Shepherd showing aggressive behavior near school. Please handle with caution.',
                'location' => 'Maple Street Elementary School',
                'last_seen' => Carbon::now()->subHours(1),
                'animal_photo' => 'storage/animal-photos/dog2.jpg',
                'contact_name' => 'Mike Johnson',
                'contact_phone' => '555-9012',
                'contact_email' => 'mike@example.com',
                'report_id' => 'SP-GHI34567',
                'status' => 'In Progress',
                'expires_at' => Carbon::now()->addDays(30),
                'created_at' => Carbon::now()->subHours(1),
                'updated_at' => Carbon::now()->subMinutes(30),
            ],
            [
                'animal_species' => 'Cat',
                'animal_type' => 'Abandoned',
                'other_species' => null,
                'description' => 'Three gray kittens left in a cardboard box near the supermarket. Approximately 4 weeks old.',
                'location' => 'SuperMart Parking Lot',
                'last_seen' => Carbon::now()->subHours(3),
                'animal_photo' => 'storage/animal-photos/kittens.jpg',
                'contact_name' => 'Sarah Williams',
                'contact_phone' => '555-3456',
                'contact_email' => 'sarah@example.com',
                'report_id' => 'SP-JKL89012',
                'status' => 'Pending',
                'expires_at' => Carbon::now()->addDays(30),
                'created_at' => Carbon::now()->subHours(3),
                'updated_at' => Carbon::now()->subHours(2),
            ],
            [
                'animal_species' => 'Other',
                'animal_type' => 'Sick/Injured',
                'other_species' => 'Rabbit',
                'description' => 'Wild rabbit with injured hind leg, hopping slowly near the park bench.',
                'location' => 'Green Meadows Park, Near Fountain',
                'last_seen' => Carbon::now()->subHours(4),
                'animal_photo' => 'storage/animal-photos/rabbit.jpg',
                'contact_name' => 'Robert Chen',
                'contact_phone' => '555-7890',
                'contact_email' => 'robert@example.com',
                'report_id' => 'SP-MNO45678',
                'status' => 'Pending',
                'expires_at' => Carbon::now()->addDays(30),
                'created_at' => Carbon::now()->subHours(4),
                'updated_at' => Carbon::now()->subHours(4),
            ],
            [
                'animal_species' => 'Other',
                'animal_type' => 'Sick/Injured',
                'other_species' => 'Bird',
                'description' => 'Small sparrow with damaged wing, unable to fly. Located near bird feeder.',
                'location' => '123 Garden Lane, Backyard',
                'last_seen' => Carbon::now()->subHours(1),
                'animal_photo' => 'storage/animal-photos/bird.jpg',
                'contact_name' => 'Emma Wilson',
                'contact_phone' => '555-2345',
                'contact_email' => 'emma@example.com',
                'report_id' => 'SP-PQR90123',
                'status' => 'Resolved',
                'expires_at' => Carbon::now()->addDays(30),
                'created_at' => Carbon::now()->subHours(1),
                'updated_at' => Carbon::now()->subMinutes(45),
            ],
            [
                'animal_species' => 'Dog',
                'animal_type' => 'Stray/Lost',
                'other_species' => null,
                'description' => 'Small beagle wandering alone, looks confused and hungry. Very friendly.',
                'location' => 'River Road, Near Bridge',
                'last_seen' => Carbon::now()->subDays(2),
                'animal_photo' => 'storage/animal-photos/beagle.jpg',
                'contact_name' => 'David Brown',
                'contact_phone' => '555-6789',
                'contact_email' => 'david@example.com',
                'report_id' => 'SP-STU56789',
                'status' => 'Resolved',
                'expires_at' => Carbon::now()->addDays(30),
                'created_at' => Carbon::now()->subDays(2),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'animal_species' => 'Cat',
                'animal_type' => 'Sick/Injured',
                'other_species' => null,
                'description' => 'Persian cat with eye infection, seems disoriented and weak.',
                'location' => 'Oak Street, Alley behind Cafe',
                'last_seen' => Carbon::now()->subHours(6),
                'animal_photo' => 'storage/animal-photos/cat2.jpg',
                'contact_name' => 'Lisa Taylor',
                'contact_phone' => '555-4321',
                'contact_email' => 'lisa@example.com',
                'report_id' => 'SP-VWX23456',
                'status' => 'In Progress',
                'expires_at' => Carbon::now()->addDays(30),
                'created_at' => Carbon::now()->subHours(6),
                'updated_at' => Carbon::now()->subHours(4),
            ],
            [
                'animal_species' => 'Other',
                'animal_type' => 'Sick/Injured',
                'other_species' => 'Squirrel',
                'description' => 'Squirrel appears lethargic and not moving properly. May be injured.',
                'location' => 'Pine Tree Park, Near Playground',
                'last_seen' => Carbon::now()->subHours(2),
                'animal_photo' => 'storage/animal-photos/squirrel.jpg',
                'contact_name' => 'Tom Anderson',
                'contact_phone' => '555-8765',
                'contact_email' => 'tom@example.com',
                'report_id' => 'SP-YZA78901',
                'status' => 'Pending',
                'expires_at' => Carbon::now()->addDays(30),
                'created_at' => Carbon::now()->subHours(2),
                'updated_at' => Carbon::now()->subHours(2),
            ],
            [
                'animal_species' => 'Dog',
                'animal_type' => 'Abandoned',
                'other_species' => null,
                'description' => 'Puppy tied to a pole with a note saying "Please take care of me".',
                'location' => 'City Library Main Entrance',
                'last_seen' => Carbon::now()->subHours(5),
                'animal_photo' => 'storage/animal-photos/puppy.jpg',
                'contact_name' => 'Maria Garcia',
                'contact_phone' => '555-9876',
                'contact_email' => 'maria@example.com',
                'report_id' => 'SP-BCD34567',
                'status' => 'Resolved',
                'expires_at' => Carbon::now()->addDays(30),
                'created_at' => Carbon::now()->subHours(5),
                'updated_at' => Carbon::now()->subHours(2),
            ],
            [
                'animal_species' => 'Dog',
                'animal_type' => 'Aggressive',
                'other_species' => null,
                'description' => 'Pit bull showing signs of rabies, foaming at mouth. Extremely dangerous situation.',
                'location' => 'Industrial Zone, Warehouse 5',
                'last_seen' => Carbon::now()->subHours(3),
                'animal_photo' => 'storage/animal-photos/pitbull.jpg',
                'contact_name' => 'Security Guard',
                'contact_phone' => '555-1111',
                'contact_email' => 'guard@example.com',
                'report_id' => 'SP-EMG99999',
                'status' => 'In Progress',
                'expires_at' => Carbon::now()->addDays(30),
                'created_at' => Carbon::now()->subHours(3),
                'updated_at' => Carbon::now()->subHours(2),
            ],
            [
                'animal_species' => 'Cat',
                'animal_type' => 'Stray/Lost',
                'other_species' => null,
                'description' => 'Siamese cat with blue collar, looks well-groomed but scared.',
                'location' => 'Residential Area, Maple Street',
                'last_seen' => Carbon::now()->subHours(8),
                'animal_photo' => 'storage/animal-photos/siamese.jpg',
                'contact_name' => 'Mrs. Robinson',
                'contact_phone' => '555-2222',
                'contact_email' => 'robinson@example.com',
                'report_id' => 'SP-FND88888',
                'status' => 'Pending',
                'expires_at' => Carbon::now()->addDays(30),
                'created_at' => Carbon::now()->subHours(8),
                'updated_at' => Carbon::now()->subHours(7),
            ],
            [
                'animal_species' => 'Other',
                'animal_type' => 'Sick/Injured',
                'other_species' => 'Turtle',
                'description' => 'Turtle on back, cannot flip over. Stuck in hot pavement.',
                'location' => 'Beach Road, near turtle crossing sign',
                'last_seen' => Carbon::now()->subHours(1),
                'animal_photo' => 'storage/animal-photos/turtle.jpg',
                'contact_name' => 'Beach Patrol',
                'contact_phone' => '555-3333',
                'contact_email' => 'beach@example.com',
                'report_id' => 'SP-TUR77777',
                'status' => 'Resolved',
                'expires_at' => Carbon::now()->addDays(30),
                'created_at' => Carbon::now()->subHours(1),
                'updated_at' => Carbon::now()->subMinutes(30),
            ],
            [
                'animal_species' => 'Cat',
                'animal_type' => 'Stray/Lost',
                'other_species' => null,
                'description' => 'Older report - cat seen in park last month.',
                'location' => 'City Park',
                'last_seen' => Carbon::now()->subDays(35),
                'animal_photo' => 'storage/animal-photos/oldcat.jpg',
                'contact_name' => 'Old Report',
                'contact_phone' => '555-0000',
                'contact_email' => 'old@example.com',
                'report_id' => 'SP-EXP11111',
                'status' => 'Expired',
                'expires_at' => Carbon::now()->subDays(5),
                'created_at' => Carbon::now()->subDays(40),
                'updated_at' => Carbon::now()->subDays(35),
            ],
        ];

        foreach ($reports as $report) {
            AnimalReport::create($report);
        }

        $this->command->info('✅ Animal reports seeded successfully!');
        $this->command->info('📊 Total reports created: ' . count($reports));
        $this->command->info('');
        $this->command->info('📝 Sample Report IDs for testing:');
        $this->command->info('• SP-ABC12345 (In Progress)');
        $this->command->info('• SP-DEF67890 (Resolved)');
        $this->command->info('• SP-JKL89012 (Pending)');
        $this->command->info('• SP-MNO45678 (Pending - Rabbit)');
        $this->command->info('• SP-EXP11111 (Expired)');
        $this->command->info('');
        $this->command->info('🔍 Track a report: http://yourdomain/track-report/SP-ABC12345');
    }
}